"use client";
import {useState} from "react";
import {useCatalog} from "./useCatalog";
export default function ManagerDiscounts(){
 const {discounts,reload}=useCatalog();const [open,setOpen]=useState(false),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[selected,setSelected]=useState<string[]>([]),[percent,setPercent]=useState(20),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [y,m]=month.split("-").map(Number),count=new Date(Date.UTC(y,m,0)).getUTCDate(),offset=(new Date(Date.UTC(y,m-1,1)).getUTCDay()+6)%7;
 function toggle(d:string){setSelected(s=>s.includes(d)?s.filter(x=>x!==d):[...s,d]);}
 async function save(remove=false){setBusy(true);setError("");try{const r=await fetch("/api/manager/discounts",{method:remove?"DELETE":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({dates:selected,percent})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Не удалось изменить скидки");await reload();window.dispatchEvent(new Event("mealpoint-catalog-updated"));setMessage(remove?"Скидки удалены":"Скидки сохранены");setSelected([]);}catch(e){setError(e instanceof Error?e.message:"Ошибка сохранения");}finally{setBusy(false);}}
 return <section className="manager-feature-card"><div className="pickup-today-heading"><div><span className="eyebrow">Цены</span><h2>Скидки на выбранные даты</h2><p>Базовая цена — 350 ฿ за день. Скидка действует на новые покупки выбранных дней.</p></div><button type="button" onClick={()=>{setOpen(true);setMessage("");}}>Открыть календарь скидок</button></div>{open&&<div className="modal-backdrop"><section className="payment-modal manager-calendar-modal" role="dialog" aria-modal="true" aria-label="Календарь скидок"><button className="modal-close" aria-label="Закрыть календарь" disabled={busy} onClick={()=>setOpen(false)}>×</button><h2>Скидки по датам</h2><label>Месяц<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><div className="discount-calendar">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><i key={`space-${i}`}/>)}{Array.from({length:count},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,"0")}`;return <button type="button" key={date} aria-label={`${date}${discounts[date]?`, скидка ${discounts[date]}%`:""}`} aria-pressed={selected.includes(date)} className={selected.includes(date)?"selected":""} onClick={()=>toggle(date)}><strong>{i+1}</strong><small>{discounts[date]?`−${discounts[date]}%`:"350 ฿"}</small></button>;})}</div><p>Выбрано дат: {selected.length}</p><div className="discount-options">{[20,30,50].map(n=><label key={n}><input type="radio" checked={percent===n} onChange={()=>setPercent(n)}/>{n}%</label>)}</div>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}<div className="manager-form-actions"><button disabled={busy||!selected.length} onClick={()=>void save()}>Применить скидку</button><button disabled={busy||!selected.length} onClick={()=>void save(true)}>Удалить скидку</button><button disabled={busy} onClick={()=>setSelected([])}>Снять выбор</button></div><small>Уже оформленные подписки не пересчитываются.</small></section></div>}</section>;
}
