"use client";
import { useEffect, useState } from "react";
type Point={code:string;name:string;address:string;image:string};
export default function ManagerPickupQr(){
  const [points,setPoints]=useState<Point[]>([]),[selected,setSelected]=useState<Point|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function load(){setLoading(true);setError("");try{const r=await fetch("/api/manager/pickup-qr?format=catalog",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Не удалось загрузить QR");setPoints(d.points);}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить QR");}finally{setLoading(false);}}
  useEffect(()=>{void load();const refresh=()=>{setSelected(null);void load();};window.addEventListener("mealpoint-catalog-updated",refresh);return()=>window.removeEventListener("mealpoint-catalog-updated",refresh);},[]);
  useEffect(()=>{if(!selected)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null);};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[selected]);
  function links(point:Point){const url=`/api/manager/pickup-qr?point=${encodeURIComponent(point.code)}`;return <div className="point-qr-links"><a href={`${url}&format=png&download=1`} download>Скачать PNG</a><a href={`${url}&download=1`} download>Скачать SVG</a><a href={`${url}&format=print`} target="_blank" rel="noreferrer">Распечатать</a></div>;}
  return <section id="pickup-qr" className="pickup-qr-points-card"><div className="pickup-today-heading"><div><span className="eyebrow">Самовывоз</span><h2>QR-коды точек выдачи</h2><p>У каждой точки свой постоянный QR. Разместите его только на указанной точке.</p></div><button type="button" disabled={loading} onClick={()=>void load()}>{loading?"Загружаем QR…":"Обновить QR"}</button></div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="point-qr-cards">{points.map(point=><article key={point.code}><h3>{point.name}</h3><p>{point.address}</p><button type="button" className="point-qr-preview" aria-label={`Открыть QR ${point.name}`} onClick={()=>setSelected(point)}><img src={point.image} alt={`QR ${point.name}`}/><span>Открыть крупнее</span></button>{links(point)}</article>)}</div>{selected&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null);}}><section className="payment-modal pickup-qr-modal" role="dialog" aria-modal="true" aria-label={`QR ${selected.name}`}><button type="button" className="modal-close" aria-label="Закрыть QR" onClick={()=>setSelected(null)}>×</button><h2>{selected.name}</h2><p>{selected.address}</p><img src={selected.image} alt={`QR ${selected.name}`}/>{links(selected)}<p>Сканировать в личном кабинете клиента.</p></section></div>}</section>;
}
