"use client";
import {useEffect,useRef,useState} from "react";
import type {Map as LeafletMap,LayerGroup} from "leaflet";
import type {PickupPoint} from "../data/pickupPoints";
import "leaflet/dist/leaflet.css";
export default function PickupMapCanvas({points,selectedCode,onSelect,onPick}:{points:PickupPoint[];selectedCode?:string;onSelect?:(p:PickupPoint)=>void;onPick?:(p:{latitude:number;longitude:number})=>void}){
 const root=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),layer=useRef<LayerGroup|null>(null),callbacks=useRef({onSelect,onPick}),[ready,setReady]=useState(false),[error,setError]=useState("");
 callbacks.current={onSelect,onPick};
 useEffect(()=>{let cancelled=false;void import("leaflet").then(L=>{if(cancelled||!root.current)return;const m=L.map(root.current,{scrollWheelZoom:false}).setView([7.91,98.34],11);map.current=m;layer.current=L.layerGroup().addTo(m);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(m);m.on("click",e=>callbacks.current.onPick?.({latitude:e.latlng.lat,longitude:e.latlng.lng}));setReady(true);}).catch(()=>setError("Не удалось загрузить карту. Выберите точку в списке."));return()=>{cancelled=true;map.current?.remove();map.current=null;layer.current=null;};},[]);
 useEffect(()=>{if(!ready||!map.current||!layer.current)return;let cancelled=false;void import("leaflet").then(L=>{if(cancelled||!map.current||!layer.current)return;layer.current.clearLayers();for(const point of points){const pin=document.createElement("span");pin.className="pickup-map-pin"+(point.code===selectedCode?" selected":"");const number=document.createElement("span");number.textContent=point.pointNumber||"•";pin.appendChild(number);const icon=L.divIcon({html:pin,className:"pickup-map-marker",iconSize:[36,44],iconAnchor:[18,42]});const marker=L.marker([point.latitude,point.longitude],{icon,title:point.name,alt:point.name,keyboard:true}).addTo(layer.current);marker.on("click",()=>callbacks.current.onSelect?.(point));}const selected=points.find(p=>p.code===selectedCode);if(selected)map.current.panTo([selected.latitude,selected.longitude]);else if(points.length)map.current.fitBounds(L.latLngBounds(points.map(p=>[p.latitude,p.longitude])),{padding:[35,35],maxZoom:13});});return()=>{cancelled=true;};},[ready,points,selectedCode]);
 return <div className="interactive-pickup-map"><div ref={root} className="pickup-leaflet-canvas" aria-label="Карта точек выдачи"/>{error&&<p role="alert">{error}</p>}</div>;
}
